name: 'Nictiz R4 QA'
description: 'QA checks for Nictiz FHIR R4 resources'
inputs:
  fail-at:
    description: 'The test will fail when an issue of this level is detected. Options are "fatal", "error" and "warning".'
    required: false
    default: 'error'
  verbosity-level:
    description: 'Show messages from this level onwards. Options are "fatal", "error", "warning" and "information".'
    required: false
    default: "information"
  changed-only:
    description: 'Indicates whether only changed files (compared to the main branch) should be checked'
    required: false
    default: false
  no-tx:
    description: 'Disable terminology checking'
    required: false
    default: false
  extensible-binding-warnings:
    description: Emit a warning for codes that are not in an extensible bound ValueSet.
    required: false
    default: false
  suppress-display-issues:
    description: Suppress all reported issues about incorrect terminology displays
    required: false
    default: false
  best-practice-warnings:
    description: Emit a warning when best practices aren't followed
    required: false
    default: true
  steps:
    description: 'The steps to perform'
    required: false
outputs:
  steps:
    description: "Information about the status of each step"
runs:
  using: "docker"
  image: docker://ghcr.io/nictiz/nictiz-tooling-r4-qa:6.2.13
  args:
    - --github
    - --changed-only=${{ inputs.changed-only}}
    - --no-tx=${{ inputs.no-tx }}
    - --extensible-binding-warnings=${{ inputs.extensible-binding-warnings }}
    - --suppress-display-issues=${{ inputs.suppress-display-issues }}
    - --best-practice-warnings=${{ inputs.best-practice-warnings }}
    - --verbosity-level=${{ inputs.verbosity-level }}
    - --fail-at=${{ inputs.fail-at }}
    - '${{ inputs.steps }}'